spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram
    username: pictgram
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
image:
  local: true